CREATE TABLE `generated_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(255),
	`content` text NOT NULL,
	`language` enum('FR','EN','AR','ES','DE') NOT NULL,
	`theme` varchar(100),
	`tone` varchar(50),
	`prompt` text,
	`status` enum('generated','saved','scheduled','published','deleted') DEFAULT 'generated',
	`linkedinPostId` varchar(100),
	`publishedAt` timestamp,
	`scheduledAt` timestamp,
	`likes` int DEFAULT 0,
	`comments` int DEFAULT 0,
	`shares` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `generated_posts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `linkedin_influencers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`linkedinUrl` varchar(500) NOT NULL,
	`linkedinUsername` varchar(100),
	`name` varchar(255) NOT NULL,
	`headline` text,
	`profilePicture` text,
	`bannerImage` text,
	`country` varchar(100),
	`countryCode` varchar(10),
	`city` varchar(100),
	`region` varchar(100),
	`industry` varchar(100),
	`sector` varchar(100),
	`company` varchar(255),
	`jobTitle` varchar(255),
	`followers` int DEFAULT 0,
	`connections` int DEFAULT 0,
	`postsCount` int DEFAULT 0,
	`avgLikes` int DEFAULT 0,
	`avgComments` int DEFAULT 0,
	`engagementRate` varchar(20),
	`followersGrowth30d` int DEFAULT 0,
	`followersGrowth90d` int DEFAULT 0,
	`globalRank` int,
	`countryRank` int,
	`industryRank` int,
	`topTopics` text,
	`postingFrequency` varchar(50),
	`bestPostingTime` varchar(50),
	`isVerified` boolean DEFAULT false,
	`isTopVoice` boolean DEFAULT false,
	`isCreator` boolean DEFAULT false,
	`lastScrapedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `linkedin_influencers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `subscription_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`slug` varchar(50) NOT NULL,
	`description` text,
	`priceMonthly` int DEFAULT 0,
	`priceYearly` int DEFAULT 0,
	`currency` varchar(3) DEFAULT 'EUR',
	`stripePriceIdMonthly` varchar(100),
	`stripePriceIdYearly` varchar(100),
	`stripeProductId` varchar(100),
	`postsPerMonth` int DEFAULT 10,
	`aiGenerationsPerMonth` int DEFAULT 5,
	`teamMembers` int DEFAULT 1,
	`linkedinAccounts` int DEFAULT 1,
	`features` text,
	`isActive` boolean DEFAULT true,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `subscription_plans_id` PRIMARY KEY(`id`),
	CONSTRAINT `subscription_plans_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `team_members` (
	`id` int AUTO_INCREMENT NOT NULL,
	`teamId` int NOT NULL,
	`userId` int NOT NULL,
	`role` enum('owner','admin','manager','member') DEFAULT 'member',
	`invitedAt` timestamp NOT NULL DEFAULT (now()),
	`joinedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `team_members_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `teams` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(100) NOT NULL,
	`logo` text,
	`ownerId` int NOT NULL,
	`subscriptionId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `teams_id` PRIMARY KEY(`id`),
	CONSTRAINT `teams_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `user_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`companyName` varchar(255),
	`industry` varchar(100),
	`sector` varchar(100),
	`products` text,
	`services` text,
	`targetAudience` text,
	`personalBio` text,
	`expertise` text,
	`achievements` text,
	`preferredTone` enum('professional','casual','inspirational','educational','provocative') DEFAULT 'professional',
	`preferredLanguages` text,
	`contentGoals` text,
	`businessGoals` text,
	`uniqueSellingPoints` text,
	`competitors` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_subscriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`planId` int NOT NULL,
	`stripeCustomerId` varchar(100),
	`stripeSubscriptionId` varchar(100),
	`status` enum('active','canceled','past_due','trialing','paused') DEFAULT 'trialing',
	`billingCycle` enum('monthly','yearly') DEFAULT 'monthly',
	`currentPeriodStart` timestamp,
	`currentPeriodEnd` timestamp,
	`canceledAt` timestamp,
	`postsUsedThisMonth` int DEFAULT 0,
	`aiGenerationsUsedThisMonth` int DEFAULT 0,
	`usageResetAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_subscriptions_id` PRIMARY KEY(`id`)
);
