CREATE TABLE `viral_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`authorName` varchar(255) NOT NULL,
	`authorHeadline` text,
	`authorProfileUrl` varchar(500),
	`authorProfilePicture` text,
	`authorFollowers` int DEFAULT 0,
	`content` text NOT NULL,
	`postUrl` varchar(500) NOT NULL,
	`likes` int DEFAULT 0,
	`comments` int DEFAULT 0,
	`shares` int DEFAULT 0,
	`impressions` int DEFAULT 0,
	`theme` varchar(100),
	`language` enum('FR','EN','ES','DE','AR') DEFAULT 'FR',
	`weekNumber` int NOT NULL,
	`year` int NOT NULL,
	`rank` int DEFAULT 0,
	`publishedAt` timestamp,
	`scrapedAt` timestamp DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `viral_posts_id` PRIMARY KEY(`id`)
);
